Create table CHROMA8_DB
(ACCESSION  	VARCHAR(10)    	NOT NULL,
CHROMO		VARCHAR(20)	NOT NULL,
GENE		VARCHAR(10)	NOT NULL,
PRODUCT_NAME	VARCHAR(80)	NOT NULL,
TRANSLATION	TEXT		NOT NULL,
CDS_REGIONS	VARCHAR(80)	NOT NULL,
CDS_SEQUENCE	TEXT		NOT NULL,
DNA_SEQUENCE	TEXT		NOT NULL,

PRIMARY KEY (ACCESSION)(GENE_ID)(CHR_LOCATION)(PRODUCT_NAME);
