insert into CDS values ('AB000381','1 gcggccggaa ttaaccctca ctaaagggat ccctcgatca tacactatgt ggcctctgtg
       61 tctggcttct gtccctgagc accaagttct caaggctcac tgccttgttg cctatgtcag
      121 tgcttgattc cacggaatgt actccatgtg gatagagcac atttgtctat cggttcatca
      181 gttgaaggac atttgggttg tggaagacca tgtggggcca gaaaagaaga aaatcctaaa
      241 aaaaagaccc aaaatgatgc ggactgtgaa ggaatagatc agacagctga aaacccttcc
      301 aatggccaga gctggaacaa tttgagcagc aaaataaata acagtattgg attatactcc
      361 tgtgcataaa ataaatgttt acaagtccat aatgatatca ataaatgatt gaagaaagaa
      421 ggatattgga gagaaaagac caatcttctg cataagaatt caaataattt acatagatac
      481 tttgcttgaa aaggtggagc ttaaattgcc actcctcaga tgtggctgca cttagtgact
      541 tccttccaac catgacagca tggaaatagg gtgggggaat gtatgagtgt gttttcacgc
      601 tgcttagaag gcataccaga gactgggcaa tttacaaaag aaagaagttt aatggactta
      661 cagttccacg tggctgggaa gggctcacaa tcatggcaga aggcaaggag gagcaagtca
      721 tgtcttacag ggctggcagc aggcaaagcg aaagaccttg cgcagggaaa ctcccatttt
      781 taaaaccacc agatttcatg agacttattc actctcatga gagcagcatg ggaaagacct
      841 gcccccatga ttcaatcacc tccctccagg cacctgcgac aacatgtggg aattcaagat
      901 gtgatttggg tgggggacac agtgaaaccg tatcggggaa aaaacattac caggagagaa
      961 gcctggcaga tacaacacca tggaagtggt caaggtcagc atcaacagtg gtgaatccag
     1021 tgtcagtgcc tactgttgat gtggtgacag aacagtgatt cacttctgct tcagtcttct
     1081 caaaacgacc atcccaggct aaccaccagg aaaacaccag gcaaattgag agacacgcca
     1141 caaaatattc aaccagtacc tctgaaacct gtcgaggtca cgaaaaacaa ggcaagtctg
     1201 agaaactgtc accgcccaga ggagcctctg taaacatgag tatgtcccac acaggctctt
     1261 ggggggtgct agatgagaaa aggacattag gggagaatga agccaatctg aatcaagtgt
     1321 ggattcagct cataataatg ggtcaatatt ggttcattaa ttgtgacaaa tggaccacag
     1381 gaatataaga tgttgaaata gggatttcgg cctgggtgag gtggctcacg cccattatcc
     1441 cagcactttg ggtggctgag gtgggaagat tacttgagcc caggagtttg agacaagcct
     1501 gggcaacata gtgagatccc atctctacaa aaaaatggca aattagccag gcatgggggt
     1561 gcatgcctgt agtcccaacc acttggcaag ctgaggcggg aggatcactt gagcccagga
     1621 ggttgaggct gcagtgagct gtgattgcac cactgcactc cagcctgggc aacagagtga
     1681 gaccttgtcg aggaagaaga aaaagaagga gaaggagaag atagcaataa ggctctctgg
     1741 gtgtggggaa tataggaact gtctgtacta tcttgggcaa cttngctgta agtctaaaac
     1801 aattataaaa gtaataagct cctctaaaaa atgtggaaat gcctatagaa gtgaggggct
     1861 cgatggtggg gttcgtgtgg ctggcagagc tctgcaggga aatcgccaca ctgcctaggc
     1921 cacatgctta gagaagttgt tctcctggtc cccagaagac cacatcttgg gtcttgttcg
     1981 ccatgcaggc agtaacattc tgtctttggt aacctgaaga agactgcgaa tagcttgtct
     2041 caggagataa aatgccaaga taatgaagct aaggccacag gtcacgccct tcagtcatca
     2101 ttgcacagga gacgttctca caggcatggc ttgcacctag accctggtca caccctgagc
     2161 cctgccccta gacacacact taggtctgac cctggctaca cactgagccc tgatcgtgct
     2221 tccactctgt ggggcctctg gacatacatt gagccctgat cctggatata tattgagccc
     2281 cgctcctggt cacacactga gccctgatct gacactgagc ctggattctg atcacatact
     2341 gagacccatc cccacacttg gggtcatgct gtcacactat ttttgactct ggacaaacat
     2401 ggatctctga ttgtggtgca caggctgagt cctgantgtg accccacact gtgacctgan
     2461 tctggacata aattaatgct gatcttgctg tgaaattaag taattcgaaa tcaaagctgt
     2521 tggaacttta aattattttg agacttagag gagtgtgact ataagacctg aatcatgtaa
     2581 acaggcagct gtaacctttg ttcttctcat tatagattag cctcttcttt acctgcatca
     2641 ttgtgcagta tgttgtaaaa gacaacaggg tgccaaagaa gaccactttc cctcttcact
     2701 gttgatctct ttatacactg acttcccttt tacttctccc agacaaagac ttcacgacta
     2761 tcacgttgtc taagatggaa tgttaaatat acttttaaac tggaaaaggt aaacaagttg
     2821 taatcaaatt gctgtatctc ataaactggc cttgtgcgaa aaaagaaaca taagcctgtt
     2881 aaatgtcttt gttttatctg tctagaaaag caagacctta actttccagc ttcggagcac
     2941 tgacctcatt cttctagggt ctgtgttacc tggatggtca ttcttagctt tgcacttgaa
     3001 taaatttaga ctggattctg atcctttcta ttatttcggg ttgccatggc tcacattctc
     3061 aaccctggcc ctggtcatag tgattggaag atgcagtaag agctaggaac agagtttggg
     3121 ggaagcaaag gaatgccagt ttgctcagag agagagagca cttcacgaag ggatcagaga
     3181 acagctgggg gctcaggctg atggggctct taaaggggca tgagccggga ggcaccggga
     3241 aaaagctggg cattgcaagg tgccccagca cctgctcttg gccatcctgc ttctttccct
     3301 ctttccttcc cacccagaac cttgccctgc aacccctttt ctccctgctg cctctggcct
     3361 cctggagcag ggagtacacc agcttttgga aacccatttt gaaggatccc agcctctggg
     3421 ctccaggctc actgagtgtg gcacacagct gcaccatgaa tgcttgccca ggcatgtcca
     3481 ggctggtccc tccctgagct gtgctggctc ctttgggagc agagactggg gcggggaggt
     3541 ggaggacaca gatgattcac tctgggttcc caggcaggct gggtgcacat gtttccagct
     3601 gatctggcta gccaggagcc aggatgcaag gatgcctgtg ttcctgagcg tcgggtgtgg
     3661 ctggtttttg ccaggagcaa ggaggtggca aactggctaa acaagggtgt ctaggcttct
     3721 gcctcagctc ccagcaggct gcagggctca cccggcacag ctcagctcgc ctgccctgca
     3781 gactggggct gagccatggt ttgctcctgc agggcctaca gctgggggca ctggaggtgg
     3841 cccggcaagg gtcattagga gctcaccagc caggcaacac ccgcaagggc ttccttctcc
     3901 gaacacactg tcttgaagtt ctctgcccgc gaagtggggt ggaaattcag cacccccccg
     3961 agcagagcct ggccgcgaga tagatgactt gccctgttta aagcggtgcc cagggacagc
     4021 ctccacgtca ccatcactca ggctccctct tgcagcccct gctggcaaag tggaaatgtg
     4081 gcttgcagag ttgcgtctga agccaagcag agggtgggaa cggagccaaa ctcataactg
     4141 aaccaccagc acccccgttg ggcagccccg gaagtgcacc ctcggggtcc tgcagcggag
     4201 aggagctggc cccacctgcc agccccatgg tgctcccagc cagtgatgag gcatggcggg
     4261 ggctgctcct ctgtggcctc ctcttaggga agcttcggct gggatgtctc tgaggccagc
     4321 cgacatctca aaatggcccc gccatccagg aggccccctc cttccgcaac tgtcagagct
     4381 atgcggagtc ccacagctct cgcctcccac tcctgttccc tctcatcctt cacaggcttt
     4441 tctggcaaaa tgttcttgca catagagtcc tgccttggca tctggtgtgg acaacaggat
     4501 ccagtacacc caaagcccct ctacaagaca gcccccatct gcttgcagac gccccggcct
     4561 cagccctgca cctttcctgt ctcacacaca tatacgatac acacacactc acacacacac
     4621 aaaatacact cacacacaca aaatacactc acatacacaa gacacacaga cgtgtactca
     4681 cacacaagca cagggacaca cgtacacaca tacccacaca tgttacacgc acacattcac
     4741 accttataca cacagacaca cattcacaca catagacgtt acttacacaa gcacatgcac
     4801 acatgtacac acactcccac acttgcacac tnacacacag acatgcactc acaggcgtat
     4861 gcgtacatgt gcacacgtat gcacacttac tgatgtgcag tcacacgcta tacaccgaca
     4921 cacacacgca gtcacacacg acacacacac ggcctgcact cacatgcaca ttcacacaca
     4981 ttcacgatac agacatacac atgcacacag gtacattccc gcagacgcac actcacacag
     5041 tgcattcata cagtacactc acactcggac aagcactcac acaagcatat tcatacgtac
     5101 atctactcac acacgtacac acacaagcac actcacatca gtgacacaca ctggctcaca
     5161 tgtgcactca cacataacac atcctctttc acacatgcac tgacattcac tctcaaacag
     5221 ttgcacacac acacatttac atttactcac acacacaatt acagttactc acaaacagtc
     5281 acaatcacac tcacatttgc atgtggacac acctgtaagc acacaaacac ttgtgcacac
     5341 acctgcacac tgtttggact gcactcacac accaacccca gagtgcacca ggcttggtcc
     5401 agccccccgg cgcttccccc gcgactgacc gaggctggtg taggagggag ggaggaatct
     5461 gtcccccctc cggaggggag atgagggcca ttccagagct tagctgctcc gctgcctctc
     5521 atcaagagca gggccaggga ggcccaacgg cttcggggag tcagagtcgg tggaccaggc
     5581 aggaggaggg taggacctgt ggctcccctt ccacgaccac actgtgtcct gaggtgcctg
     5641 gctctgggct ctggcagacc aggtttttca gtgtgggctg catggccatc tccttcctct
     5701 ccttaacatt ctttttccat gaagtgggaa tcatgatccc tccagcccta agttgtcccc
     5761 agaattaaag gggcatgtgt gtgtctaaca gagtcctggg accaaggaaa accccagaga
     5821 aacaggggga cggtgctgtg aaaaggaaga gttggctgtg agggcctgat ccaagtcacc
     5881 taggaagatg ggggcaagag ggacccgggc ccagggagcc gcggagccgg ggaggagtgg
     5941 ggcgaggtct gtggccggct tcaccgggcc tcctctgctg cctgcccact gctccccaat
     6001 gctgggcagg acctcgagtt tcctcacctg caggacctcg actttcctca cctgcaggat
     6061 gggtcctccc ctccggcctc tgctcgcctc tccttctcct tcccaaactg cgcagctctc
     6121 agcaccctct tcgggccact cccagcaccc agcaaacaca tctaaaacag tgtagcacag
     6181 ctcacaggcc ctggcacgct gtgggggctg tgacggggcc cagcagacca cggggacgac
     6241 gagcatcatc agagagtaac ctgcaacctg gccatgctgg gtcctcctgg ggacctgact
     6301 agcaggaggc acccttgagg tctcggtggt tctggggccc acaggcttca gatctggccc
     6361 gtctcccatc ttccactctt ctccacggct cactttgcct gaaaaatagg ctaatgctgc
     6421 ctgctctact ggccagctgg ggaggctctg ttggtgaaat gagagcccat aggctggaaa
     6481 gtgtttgaaa catttgaagg cccaagtctg gaggggaggt cccaaggtcc actcagatcc
     6541 tgagttcatt ggctcagcct tggggcgggg ctctcgctcc cggaagggga tctgcctggt
     6601 gaagcccagg ggagtggatt caagtctaag tccgccgctg tggatgtggg ggctgagcaa
     6661 accactcagc cctctcagag ggcctcatga gggtcccaat ttctggcctg ccagggcatg
     6721 acctccctgg agacctcact ccagacgcct agaagtcagt gaccctccag caagagggag
     6781 aggagcccgc agccagggct gctctgatgg acgccacagg gccgttccga cccatgtccc
     6841 agactccttt taacacaggc ctcctctaga agtgttttcc aagtgctggg ggtggtaaga
     6901 agggggttcc aagaactgcc cagtttggga acgagagggg gtgggagaac tgagaggggc
     6961 tgggtcccca gggccagttg tactgaggag gaggcttccg acagccctgg gcccccaacc
     7021 ctctgctggg cttctgggaa gcaaacgcct aagtgtcctg ttccctgtag cccagctaag
     7081 aaagaccctt gagggaagca ggcagccaca gaggctgtac agtcttggga gccgtggcac
     7141 agcccagggt gggccaggac agtccccgtc cccctcacag ccctggggag ggtaaggcag
     7201 agcccatcag gctgtcccca gagacgccag ctacctcctg ggccaggaga caggagtcgt
     7261 agtccttgtt tagaggttgc ctaggggaag ccctggggga gatggacagg aggaggacgt
     7321 ggctaagagc tggggtgggt gttgcggcct ctccaggagt attctggaga gaatttccta
     7381 aacagaacag gctctgtgag gccacccaca cttgctgcct gctggcgacc cctggagtgg
     7441 catcccccct ccccacttct gtgggaccct cagacacagc cgtcgccatt gctgaatgac
     7501 cgtcgctgcc acacggccag ctggaccatg cccacaactc accaaagggc cagaggcacg
     7561 actcaccgaa ggggtagagg tgggatcctg cccactggtg ggaggagagt acagagatgg
     7621 actctaccca gttgcgacaa attcaggagt ttcccgaagg gactgcgacc tctgtaggca
     7681 agcccaaaac atctagggga ggccgggcgc acaccccctg ggaccaaggg tgtgagccca
     7741 gggctggcga gtgggtacct gggtgggtct gccaggtggg gagccggctc tgtctgccaa
     7801 gggccctgag ggcaggatgt ggtctgccgg acagcacgtc tgctcacaga gggaccacct
     7861 caggagggct ttcttctgag cagttgtgcg tcctgtgctg agcaccttgg ggaaactgag
     7921 acaggaggta gtgtggagcg gtgagtatcg tggcaggggt gcctcttcac cagctnacgc
     7981 cgcaaagcca gcctacccca gcctccagcc ctcatgggcc ttggaacccc tccgggcatt
     8041 tccacagccc actcccagga aagcctggct cacaggtaac cagagcacac tcctatcaca
     8101 gtgagtccca cagcacccat gcctggatgc tggccaagct caggcgcctg ccactgccac
     8161 tgccactggc tgtgccctgc ctgcaggtct ccctcattct accctctcct cagattctct
     8221 cctctgcctc ttccaggaag cctcccgtac tccacccaga gccctcttgt cctgaattcc
     8281 tggggttctt tgggcttcgg ggataagtgg gtgtgcagct gtcgtgtccc taggtgaaag
     8341 ctggaccagt gcccagcctc cccgatggcc ttcttagggc ccaccctgca aacctctgct
     8401 ttatcttcca gatacaacct cacccatgaa gggaaggcca cgcctgcatc ccttagggtc
     8461 agaagccaag acgccctgca ggctctgcac ctgactctgg agcctaagat ccctagaagc
     8521 agggcagtgc tgcctcccta cagcttagtc ctgcccatgg tgggtccttg gttcagacat
     8581 tcattcattc cctcccctcc cccctgcccc atgttataga caggctggct gggccctatg
     8641 ccgggggtgg gccaaatcct gcatgtgcag aaggatcccg tgagagcctg cccacagcaa
     8701 ggtcggtcag aagggatggc tgaggcacaa ggggcggggt ttacacccca ggtgggggca
     8761 gcaccgtggg gtgcaggagc ccacagggag ggtgcagggc catccagcaa ggccagcctg
     8821 cacaaggccg ttcctgccca gtccaggtgc agagccttac taggacctgg gagagcaaag
     8881 ggacaggcaa ggtcatacct gcgggggtgt ggggctcctc tgctgggcct agacgttgag
     8941 ttcatacccc tttgccaggt tgggagaggg catcggctgg ggacaaagcg ggtcaagcag
     9001 gtatgagatt acccttggat ctcttcctcc tgcagcttgg aggatgccag caggggccgg
     9061 cgttgaggag gccctcgggt ggcatcacca gcatggctct gagggtctct atttccagag
     9121 ctctgcatct gtgagctcag gcaccccacc cagtcagcga gggagaaggc aggccgctcc
     9181 tcagtggaca catgccagtg gcctcaggtc ccattgctcc acctctcgca gtggaaggcc
     9241 acccccaatg tgctgagtcc actcagcaga agggaagcgc tttccctgag cttgcaggac
     9301 tcggcccaga gcccggtgct tagagggctc tgtgagcctt tgggcccagg gggcctgtag
     9361 acgcctttgg aggctggaat gtccgtggaa agcaccacct tgctgattct gccgcagagg
     9421 ctgggctggc atgtgggctg gggcttgtcc taacactggg accctggcag gtctctgggg
     9481 ttgcaggcag gaagcaggta aggcttccac actacagcct gtatgaggtt gtataaggta
     9541 aagcattcat gtattcattt gctcggcaag tattcattta cttcctacat gctggacact
     9601 gtgctgggta tttgccacag tggccttgac tggcatccac agggccagca gcttaagggc
     9661 acacagcctg ggggccatgg gggtggtaag aatgtgggcc tgagatggtg ggaaatgcct
     9721 cctgcacgga aaacatgctt cccgtagtcc caggcagctt agaagaccta ctgatgagca
     9781 tcgaaacaga atcctgctcc taagcctggc tgtgctctcc cagtgtgagg tctttggttg
     9841 ccgtccatgt cattgtcctc ctccttacca caggggccct gggcagccaa ccttggcaat
     9901 attcatgcag atctaatgaa accatgccca cagacaccgt ctgtgcccct gcctggatac
     9961 ctcatgcctg tgcctggttg gaggctgcac atctttggct ggggtttgct cttggcgtgg
    10021 attccatttt ctcccagcaa ggtaggtgtg tagagggggt gtttttctag caagcagcca
    10081 gtggttcgca tgttttttca tacatggcat gtggcattag caatttaaat ctccaccttt
    10141 ggctttgatt tttagcatta aaaggaggaa ggggtaagtc caggttgaaa tttaggtcta
    10201 aagagacatg tgggggttna gggaagtccc tagccccgtg cttcaggggg ctgattcgat
    10261 gcaagttagc tgagcaagag ctcgagtaag gggatttgtt attatccctt aggccagatc
    10321 accacagaag ccagccagcc tgcttcattc cccctgagag atttcatctt cattttaagg
    10381 ggttttgggg caaaggtctc ttcttctgga gctacttcct gctgaggcga gtgtcattcc
    10441 tatatccttt acctttacct gagaggaatg gaactccttt cagcttaagg ggacaatctg
    10501 ctagggctga gggcttctgg aacacactgg aagcactgca cggtcagtaa cattgttgca
    10561 atctagaaga caaaagtttt cccaggaagt taaacaagca tggtccaaaa atcaaaagaa
    10621 ggatagccgc tgatggtcct aaggaaggaa gaaaccaact tgtagagaga gaggtgatga
    10681 ggcagcattc ggaactgact cctctgctgg gctcccttta ccagagagtg tggccacatt
    10741 gtctgattgt agattgcttg gatgttcacc tctgcttgcc ctgtagtatt tatctaagca
    10801 tggcaggagg tgttggtgac tatgcataca cctccttgtt ctgccgttag gtaatcaagg
    10861 gccaatggtt acccaacacc acgttatcga aagaactgag ggaaggcttc acaccttcta
    10921 gagcctgccc agtctgatcc actacatgac cgatctgcca tgtcaggcct ccccaagggg
    10981 ctggtaaacc aatactcagg cctattccca ctggcgccat gccaaggcct taccttgctc
    11041 acacagtggc ctgatgttgg gaggtgcagt tgtggttact ccgtttatcc ccatcgatcc
    11101 caaggcacat tcacctgtga atcacacatt ggctctgcag gaataggcct gagccaacag
    11161 aggaaaagta taaggaaagc aggcagtgga ccacaagagg ttattagggt ggcctcgagg
    11221 gataacaatt ccaagaggag cccaaattcg aatgtccctg gtgtcattga gaatggagag
    11281 gttcaggtta tgaattgtgc agctgggggt atcaagccag ggtcctgatg atggtctgca
    11341 tatcccctgg tgtcattgaa aatggagagt tcacgttatg aaatgtgcag tcgggggtat
    11401 caagccaggg tcctgaagat agtctgcata tcccctggtg tcattgaaaa tggagagttc
    11461 aggttatgaa atgtgcagtt gggggtatca agccagggtc ctgaaaatag tctgcatatc
    11521 ccctggtata tatcatttat ataaggatgt tacttaacta ttgctgtctt ccagaggcag
    11581 cttcttgaac aaatacttga ggtccgctat aggtttatgg gagtagactg ttttctccaa
    11641 gcaggcctgt cgtccatcag gaaaagcaaa aggttttatt ctaaaaacaa ttccttccaa
    11701 ctgtacagct gatggagtgg ccacggaaac ctggtatgga cccgctcatt tctcagtgaa
    11761 ctgagcctct gggcttcctt ttccgccatg tcttgagtag gacctgtgca cctgggctag
    11821 cagggcaaat gatctgaaac tccatgaccc ggctgaggtc acatcttatt atcatattgg
    11881 aagatggcct gctgaacttg tcccaagtta atgatgtatt ttacagcctg atttagctct
    11941 tcgtctagaa gaaagtggct aggaagaggc tagcaataag aggagtgggt tgggatcctg
    12001 tcggcatcct atgtcacgct tagacaacga tgctcgccta gaaactcagg ttagaggctc
    12061 ggcccacaag gttatatgcc ctggggtata tctggaccaa tggaatctct ttgcaagatg
    12121 tttgtccgtg tgtgatctga actaatccac cttgtgccct ctgctgggga tgggaaagct
    12181 ctacttctca tcatttccca gctcattgct ttgctgtaca gcagccttgg ggcagccccg
    12241 aatggctggt ccagaggttt ccaccttcca gtggtggatt ctaatgttct ttatgtgttt
    12301 ctctctgttc ttctctgcct gctttggatc ggctgttact aagctgctgc cgagtggcaa
    12361 ctctgcttat ctcacggtgt tgaggtgaga ctcactgctt ttggtattac tgattcaagg
    12421 ctacttagag attgtctttt cttgtacagt tcagccagtt ctggctaaaa tgtatacatt
    12481 aaaaactcat ttaaaactga agaaaaaagt gatgaaaagg tttttttttt tttcttaaaa
    12541 ccaaacttcc ttaaagacta ctttaccaaa actttggtcc acagctttcc ttggattgct
    12601 tgtatgtctg ggtcaattaa gaaaagttta tgctctggga aacatgtttc tagaattgcg
    12661 ggtcttatct ataaagtgct aacatctggc aaacagtgta ggatctcttg cttcctcggt
    12721 tttcagactc acagatgaat gaatgccctt aactgtccct tcccatccct tcccatccct
    12781 tcccgctccg gtttcctgta tgcaatgggt tcagccttcc gagccctggg agaagcaggg
    12841 attctcatgc ttctttatgt tcccctaggg actaggggtt agcagtcctc accccaatgt
    12901 gtgaggtcct ttgggcttta tttgctgggg agcctggagc cagggatcct ccaggtcagc
    12961 cactacccgg ttgcatgggg cttttcggcc tttaggggcc cagggttgca gtgacacccc
    13021 aatggagagc ctgtttgagt ctcagaggga tatttgccag cacatactgc taggtccctc
    13081 ttgtcccctt tgtcagctgt gtatttgctg tctgtgcctc attagtgaca tctgtcatcc
    13141 tgagcttgca tgctctgaag tttacacctg ccattttcct tctggtcctg gtgattttca
    13201 ttctttgggc tatttaattt ggcatctctc tgggcaatgt tggaggccaa aagcctccca
    13261 ggaactagtc ttattgagaa gaaaaataat tttgtctaat tcagaagtta tctaaaggtc
    13321 aattcaaatg atgaacttga aaacagttac ttacaaaaca agttagaaaa gagccagtaa
    13381 gtaggggagc gagagatgtg aataaaagtt atgaatatga agatgtattt ttggtaagga
    13441 aggttatcaa gaaaagagaa taacgttgta tgaaaaagga tcttgtatgg taaatttttg
    13501 tcctaaaata aaatggctga ttatttagga aagagggaaa gtttgggcaa ggcagaaagt
    13561 ccaagcatgt cttcaatgat ctgtgtatgt cagggtcaag ttcatgaagg ggaatttatg
    13621 aaagaaattt cgtatgtaat taagttggtt attattaaaa ggaagccact tataatagtc
    13681 tttctaaaaa ttggtctcct atgttaaaac aaaatgttct taaggcactg atttgctctt
    13741 aatgacatta caagaaattt tactttcact ttttttttgt ttgttttgtt tttttgagat
    13801 ggagtcttgc tctgtcgccc aggctggagt gcagtggcgc aatctcggct cactgcaagc
    13861 tccgcctccc gggttcacac cattctcccg cctcagcctc acgagtagct gggactgcag
    13921 gaacccgcca ccacacctgg ctaatttttt gtatttttag tagagacagc gtttcaccat
    13981 gttaaccagg atggtctcaa tctcctgact tcctgatcca cctgcctcgg cctcccaaag
    14041 tgctggaatt acaggcatga gccaccacat ctggccaact ttcactttta taaactgttt
    14101 ctctcgaaaa cttctctttt tttttaaatt tttttagtat ttattgatca ttcttgggtg
    14161 tttctcggag agggggattt ggcagggtca taggacaata gtggagagaa ggtcagcaga
    14221 taaacatgtg aacaaaggtc tctggttttc ctaggcagag gaccctgcgg ccttccgcag
    14281 tgtttgtgtc cctgggtact tgagattagg gagtggtgat gactcttaac gagcatgctg
    14341 ccttcaagca tctgtttaac aaagcacatc ttgcaccgcc cttaatccat ttaaccctga
    14401 gtggacacag cacatgtttc acaaagcacg gggttagggg taaggttata gattagcagc
    14461 atcccaaggc agaaggattt ttcttagtac agaacaaaat ggagtctcct atgtctactt
    14521 ctttctacac agacacagta acaatctgat ctctctttct tttccccaca tttccccctt
    14581 ttctattcga caaaaccgcc atcgtcatca tggcccgttc tcaatgagct gttgggtaca
    14641 cctcccagat ttctggggat ggtggccggg cagatggggc ccctcacttc ccaaaagtgg
    14701 cggccgggca gaggggcccc ccacctccca gacggggtgg ctgccgggcg ggggcgcccc
    14761 ccacctccca gacggggtgg ccgggcagaa acgctcctca cttcccagac ggggcagctg
    14821 ccgggaggag gggctcctcg cttctcagac ggggcagccg ggcagaagga gctcctcagt
    14881 tcccagacgg ggtggtggcc aggtagaaga cgctcttcac ttcccagaca gggcggccgg
    14941 gcaaaggcgc tcctcacttc ccaaacgggg cagctgggca aaggtgctcc ccacatccca
    15001 gaagatgggt ggccaggcaa agatgctcct cacttcctag atgggacgac ggcagggaca
    15061 gaggcgntcc tcacttccca gactgggcgg ccgggcagag gggctcctca catcccagac
    15121 gatgggcggc caggcagaga cgctcctcac ttcctagacg gggtggcggc cgggcagagg
    15181 ctgcaatctc agcactttgg gagaccaagg caggtggctg ggaggtggag gttgtagcga
    15241 gccgagatca cgcnctgaca ctcccagccc tgggcaacat tgagcactga gtgagcgaga
    15301 cttctgtctg caatccccgg caccttcggg aggctgaggc aggcagatca actcgagttc
    15361 aggagctgga gaccagcccg gccaataggg cgaaaccccg tttccaccaa aaaaatacaa
    15421 aaaccattca ggcgtggtgg cggcgcgcct gcaatcccca ggcattcggc aggctgaggc
    15481 aggagaatca ggcagggagg ttgcagtgag ccgagattgc ggcagtacag tccagccttg
    15541 gcaacagagg gagaccgttg aaagcgggag acggagacga gggagagggg gagaccgtgg
    15601 aaagcgggag atggagacga cggagaggga gagggagaag gagaggcaga ggctcaaaaa
    15661 ttttcagatc catatttcag tatttcagac attccatttt ttctgtttca ctgctttcag
    15721 ctttttcccc cttgagcagg cctgagatga tgaccttctc cttcagcatt tttttgtcgg
    15781 ctcctgcacc ccttttttcc tccagtttta actgttggaa tgacctgatg ctaatgtttt
    15841 agtttgaagg tttagaaaag caatgttttc ttttagtata agttgatttt atatttcttg
    15901 gcttttcttg ctgtgtctaa attttcagtg taatcagaaa acttctcatg ctgttcctaa
    15961 gggtcacata tgctcataga ccttaaacac tgttcctgtg tctgattgca ttcaagcact
    16021 tctttcctca agtttgtctt ccaggttatc taaatgggct tcctgtaaga agcagcggtc
    16081 tcactgcaga aggttttctc tgccttttta tcagctggct ttactttttt tttttttttt
    16141 ttgcaactgg gtctcacttt gttgcctagg ctggagtgca gtgacacaat ctcagctcac
    16201 tgcaacctct gcctcccggg ttcaagccat tctcttgtct cagcctcccc agtagctggg
    16261 actacaggca cctaccacca tgctcagcta atttttgtat ttttttggta gaaatggggt
    16321 ttcaccatgt tggccagtct ggtctttaac tccctgacct caagtgatct gcccacctcg
    16381 gcctcccaaa tttctgggat tacaggtgta agccaccaca cccagcctat cagctggctt
    16441 tttttaaaaa tgcaagattt tatattttat caagataatt tcttatgctg tctttattag
    16501 gttttctatt gaaaaaaaaa ccctgaaatt taaaaggctt aaggttttta catccatatg
    16561 actttctgta ttgctcgtaa tgtcttcttt attattactc ttggttaaat gtgtggggaa
    16621 aagaaagaga gatcagactg ttactgtgtc tatgtagaaa gaagtagaca taagaagctc
    16681 cattttgttc tgtactaaga aatattcttc tgccttgaga tgctgttaat ctgcaaccct
    16741 acccccaacc ctgtgctcac agagacatgt gctgtatcga ctcaaggttt aatggattta
    16801 gggtgcagga tgtgctttgt taaacaagtg cttgaaggca gtttgcttgt taaaagtcat
    16861 caccactctc taatctcaag tacccaggga cacaatacac tgcggaaggc cgcagggacc
    16921 tctgccgagg caaaccaggt attgttcagg gtttttcccc acgtgataat ttgagagatt
    16981 gccttgtggg aagggaaaga cctgaccgtc ccccagcccg acacccataa agggtttgtg
    17041 ctgaggagga ttagtaaaag aggaaggcct ttttgcagct gagataagag gaaggcatct
    17101 gtttcctgct cgtccctggg caatggaagg tttcggtgta aaacccgatt gtatgttcca
    17161 cctactgaga tcggagaaaa ccgccttaag gcaggaggtg agacatgctg gcagcaatac
    17221 tgctctttaa tgcactgaga tgtttatgta tgtgcacatc aaagaacagc acctattctt
    17281 aaacttgttt atgacacaga gacatttgtt cacatgtttt cctgctgacc ctctccccat
    17341 tatcgcccta ttgtcctgcc acatccccct ctccgagatg gtagagataa tggtcaataa
    17401 atactgaggg aagtcagaga ccgcaggtgc gggtcctcct tatgctaagc gccggtcccc
    17461 tgggcccatt attgtttctc tatactttgt ctctgtgtct ctttcttttc tcagtctctc
    17521 atcccatgtg acgagaaaca cccacaggtg tggaggggca ggccacccct tcaaaatgaa
    17581 taactgtcac aatgacctgt gattctgttt tgatcaaatg ttttgagcct tttaacatct
    17641 ttaacaaata ttctcaaaat caaaatccta aattaagtct ccgatttagt gtcctcgctg
    17701 gggcttatta aacctataaa aattaatctc tgtgaggtta taaaatcttt gtctagcttc
    17761 caggtagacc atgaactcca gtatcaccac ctccagcctg ataattatat attggaagaa
    17821 aattagttaa aggattccct tcagccccct tgaaactgcc cttatcagga gttgttagct
    17881 aatccttgtg ctcagttaat aacctgttgc aggcccttga ctcctgggca cacatgtcta
    17941 aagaaggcac tgacttccac cagtatctga caaaaactca agttaactga aggctcgtct
    18001 ttagacctgg gcaaagggga caacgtaaac tgctttcatg agacacaagg acaggcctgt
    18061 attccaaaac attatgattc atttcataat tttgccttta tctgaaataa tataatttgt
    18121 tctatgcctt tatactaaat aatttaaatg tttaacttat ttcctggcat tctcaaaatt
    18181 agatagggct tatgaccttt tctttaaaat gttgttaatt ctttatgttt tcttttacct
    18241 ccaaaattta ctcccaccag gcccagggag tgtcataagt gttttcaggg ccagttttga
    18301 ggaataaaat gagtgcaaac cttccaaata aaggacaggc acacaaatgc ctaaatggct
    18361 gaacaaagtg cttgtgtttt gtgtagctaa ttgccgcaaa ccatgatgac agtagctcat
    18421 acacagaatg tataaagaag ccaattttgt aaccttgcct tttggctttt gatttttggt
    18481 tctcatgttg ctgaaggggg tttaagatta atgagtgcct gcccacctac attcccatct
    18541 ggcctagagt acttcattgg ctctaagtct tttgactcaa agtcccttgg ccacaggaat
    18601 tcccaccaag gggcatgatg gacccggggc aggctgccca ccactccgac tccagtgtcg
    18661 acatgggccg caatagaagc atggctgttg acactgccgc tggcatacgt tgaccacaaa
    18721 aggaggaaaa taaacgtaaa taaataaata aaatcctaag cacccccatc cccagcagaa
    18781 tggggccccc ttaggccaca gaacctgaga aactagttta ggccagagag gggggaagtg
    18841 gagctggtag tcagagggcg gggaaggcat ggacaagcct cactatacct ttcccccacc
    18901 ttggaattca ggcacaactg accagcatta aaattaaaag aggtcataag actgacaaaa
    18961 cagactggat cgaaggccct gccaggcagg attgaagttt gcaccccagg gtagacagag
    19021 gtgtaagtta caggaacgtt ttaaaatatg tttgcgtcag gaccaccttc atgaatattc
    19081 atagctcctc tgttcaacca gaagacttca tcttattaaa aacctggaaa gaaggatcct
    19141 ctgaggatca gttacagccc agatggaggg gctcatcagg tattgttaag cacccccatt
    19201 gccgttaaac ttcaaggact cactagctgg atacacctgt ctaagattaa gcccgtttct
    19261 tatgagtccc cacaggcacc tgagaaagac actatggcca acacctgtga actcttagaa
    19321 tacctaaagc tgttgttttg gaaataaaca gataactagc atcttagtat ctccctccta
    19381 ctcagcctcc ttaacaactc tcatcccata caggtttgca cccccagtgg atacctatgg
    19441 tcatgtggtc acctattcaa tcagcatata aatagcttat ctctcatttg ggaccatgaa
    19501 ctcaatggtt accagcatat tgacaacatt tggtcagggg tcaatgtaca acaccctata
    19561 atgtacaatt atataccatc acttacctga gagctaagtg ggcaattccc cttatattgg
    19621 ctggggttga gcctgccatt ggcttaccca ccccatgggg aaaatttgcc tattatgagg
    19681 caactcttca aaactttact tcttcattct acgcactgtc tcataaaaca ggagacactt
    19741 tagaaacatt aaaactctcc cttgattcct ttgcagatat aataattgat gacagattag
    19801 cacgagagta ttatacttat gggttgaaca aggagtatgc actataagta ataaaacctg
    19861 ctgcacttac gtaaacacct caggtcaaat agaagaagat gaacgtaaaa tatatgagcg
    19921 agctgcccag tgcataaata caaccaaggc tgtgatccta actatagctg gtcaacaata
    19981 aaaagcaccc tcctgagtct cacttggttt ttgcccttcc taggaccttt gatatttatc
    20041 tcattattag taatctttcg cctttgcttg tttaacttaa tggtaaagtt tgtgtcttct
    20101 agattacaac aattccacat aaagattatt ctggcaaccc atcccgtctt ctgaccttgg
    20161 aaataaagac atcctgcctc aggcccctta gatcaggcat ccagagattt ttacacctcc
    20221 aatactaggc aaagcataag cccatagaat catcagtcag gctggagtta gaacgtatat
    20281 gactatgtga tcgtaaaccc cagacacaaa aaccacttgc aagtggtcat gagtcatcct
    20341 caccctggga agcgaacaga aaccatcact ggagggggac ataccctcca ctcagacccc
    20401 cagcctctgg tttactaatg acaaatacag atatgccaca gataaccaga ggcacagaag
    20461 tgattaagcc cccaggagca aaggcagaag aaacaaagtc tccaagttag actcccaagg
    20521 aattcccata ggaatgattg gaggcaaatg taaacataca gccttgaaaa gcaggaaaaa
    20581 atcaggtcac ttccacttct acatgggatg cagtaggttg tggctgctca gaatgtgaca
    20641 accaggcaaa tcaatccaca gagttaaaag tcacatttga aaggcccttg gacagatgtg
    20701 gaagcaccaa ggcctgcatg aactgaaatt ccgcagaggg cgagcccttc cagggtacct
    20761 ttgtcattgc aaatacattt gtcactttgg gcaccagctg aaagccaggc tggctacaga
    20821 cagggactcc agtagggaat gcaaaccagt agtgccgtct tggctcacgg ggaaccaaag
    20881 tggcccagaa tctccaggta cctaaagatc aagacagttt tcccatggaa gagcctccaa
    20941 gtgctgtggt gggagggacc ctggggagtc agagaaggcc aagtagaatc ccccccagtg
    21001 tggcagatcc caggagacag agtgccccta gaaggagcct gccacagtca taccactggt
    21061 ctccatcata agccagtggc cccgatggaa caggtgtgtg ggatgaggtt caaggggaaa
    21121 gtcaaagcct agacagggaa acctgtccga gctgaggatt cggtgtgaaa ggtgagcata
    21181 caaattgggt cacccttgtc acacccaact aaggaagagt gccaggtagg gagaccatcc
    21241 agaactcagg atagaaaaca tggttccaag aatgtactgc tctgaggcct gattgttgaa
    21301 actgcctggg gcaacctgaa accagtttta tctgatggtt actgagacca cctgctgaaa
    21361 ctctaagcct cggttcaccc actgttgtca ctgattcact catcacccag cgttcgccag
    21421 ctccccaaat gcctactagt gccaatgaaa ctcagacagg aatatgtact atttctcttc
    21481 tttataaaaa agagacatag ttcctttttt tttgagacag agatcttgat cttgtcgggc
    21541 gggtgggagc acaatggcag gatctcggct cactacaacc tccacctcct gggattcaag
    21601 ggattctccc tgccgtcagc cgtccctgag tagctgggat actggcacac accaccacac
    21661 ccagctaatt tttgtatttt tagtagagac ggggtttcac gatgttgatc cactctggtc
    21721 ttgaactcct gacctcaagt gatctgccgg cctcagcctc ccaaaatgct gggattacag
    21781 gtgtaagcca ccgcgaattt aaaaaaagcc ttttctttgt tctttggaca tactgaaggc
    21841 cagccagtct gcccccgtgc ccctaattgc agttatttcc tcccaaataa aacatttcag
    21901 aaattcacct attttatatg acttcgacaa gagccaagcc acactgtgta ggagatgctc
    21961 gggtgaagcc agctgtccct ggccacacac agcttgaagg caaaatggcg ggagctcaag
    22021 cgaagccagg caggtctccc cctgaaacct ctgcacaggt gggcgctggc ggggctgaag
    22081 ggcaccgctc aagctggctt tggtcagggt tagggacagg gccggctcca gagcgacggg
    22141 gtcgcaccct gagcggaggg gctcccgggg tccccagggg ttatggtgat ggcgggaccc
    22201 cctagaggga gggtccagga acgaggcagg tggactggga ccttgagggc agggtgggcc
    22261 tgggcggtgc caacaggctg ccgagggtgg ctgctgtccc gtttctccag cagccagggc
    22321 cgtgcgcttc tagaacattc cccgtggctt tcctaaaggg agcgtggatg gagccagggt
    22381 gtgcagattt ctgtgagaaa tattttcacc tgggagcccc aagggggacc ctgcccacct
    22441 ttgaacactg gcagatgggc tggaggcctg gagcctgggg acggggcttt gagggtccgg
    22501 aaggagggcg gggctgtgcg gccggcggag gcccccgaaa gttccagaaa gcgggtgggg
    22561 aggtcggcgc gggaggctca aatggctgga ggcggcgggc acgcacactg cgggctccga
    22621 ggggcacagg tcagtttcct gaggcgggtc gggacccagg cgtgagactg gagtctgccc
    22681 aggggcccag ctgagccagc ctcctcgtca gctgcttggg ccgccaggac gccgccgggg
    22741 gtgcgccgcg cttccctgga tggggtgccc ccactcccct cggagcccca gggagacccc
    22801 ccgaactcag ctcctctcag gggtgccagg gggacccctc aaactccact ccccgcaggt
    22861 tcctggggag acgccccctg ctcgattccc ctcagggtcc cagggagacc ccctaattca
    22921 gctcctctca ggggtactgg gggacctctc gagctccact cccatcaggg tcccagggag
    22981 accccccaac tatgctcagg ggtcccaggg agatgccagc accccaactc cgcttccctg
    23041 gggcccccct ccccttacag ctcaacttcc ctcgagagtc tggggctggg gctccgttca
    23101 gttcttgagt ccccttccct cggggtgtcc cggggccgcc cacccccaca ctgtctgtga
    23161 ttccccaagg cgcgggtctc gggccgcagc ctgttccacg ttctgctgct cgttcttttc
    23221 tggctccttg ctttcgaagg agagaaggag gccttcgttt ccagtctttt tgccttttct
    23281 aatggagccc tgcttttcct tccgtgtccc ttcaggctac ttctgccagg tttctatttt
    23341 tcattcttta ttatgacttc gcccaaaata ttcttgactt ctattgagaa ggattcgggg
    23401 gtctatttct tattcggagg cgtgtgctta agttccaaac agatgaggat tttccagtta
    23461 atccttctgg ggtgacttat tgcttaatgc caccatagcc agaaaatgga ctctcagtgt
    23521 ccgaaactgc attcggctct gaagtgtctg tccttgtcac ctcttgcaat gtttcgcggc
    23581 gggaagcctg cactcgccga cgctgacgta actgtttctg tctttcaggt ctacagcctc
    23641 ctgtgggtgg gcgatattga catatacttt atttctatat atgttatgaa ctcaatattt
    23701 cttgcagcgg gtctgctgat aataagatat gcctactctg cgagtctgga agccatctta
    23761 agcttaccct gtatgtgccc catgcatctc ttccgttaca cggctcctga gttgacacct
    23821 gtgtgataaa ctggtaatag caagtaaact gttttcttgt gctctgtaag ctgctctagc
    23881 aaattatcta ggaggaggtg gtcttggaaa cccctgattt ataagcgggc agtcagcagt
    23941 acacgtggcc cagaatcgtg attggcattt gaagtggggg cagtagggtg ggactgagcc
    24001 cttcacctgt ggggtctgcc ctgctcaagg cagtgtcaga attgaagtga aatgttggac
    24061 ggtcggtgtc cagagagttg gagaactggt ttgtgtgtaa aaactnacat atttagggtc
    24121 agaagtatgg tggtgtagaa ataattcgta gtatagtccc ttagttctgc ctcttacaca
    24181 tcctgttatt tttnaaattt tttcatcttt aagaaatcaa tttagtaatc tttttatctt
    24241 taatgctctc attagaattt ttaaagtact tgtatgctaa tgtcaacatt tgagtgaact
    24301 gtgggtttat ttctattgtt gttttattga ttagcaataa tttattccta attcttacat
    24361 atcctgtgat gtttttattg aacatcttgc gttgcgtaca aaatagctgg aaagcttgga
    24421 ggtggttgta tgttactact ggggatgtgt gccctctcct ctctccagga gcctgtggga
    24481 aggcctggac tactggcttg ctcaaaggtg gaggccaagt gggatgcttg cagcttcaac
    24541 ctgaccctgg ccgcctctgg agccggccct gtctctaacc ctaactgaag ccatcttgag
    24601 cggtgccctt ccccttctcc tacagagtgt ggcttgtctc gtgttgaagc caaataaaaa
    24661 agatgacttt ctgaaattga aatcttttct ttcggaggaa ataattgtaa ttaggggcat
    24721 gggggcagac gggctggcat tcagtatgtc caaagagcaa agagaaggat ttttgaaatt
    24781 tgcagtggct cacacctgta atcccagcac tttgggaggc tgaggcaggc agatcacttg
    24841 aggtcaggag ttcaagacca gcgtggccaa catagtgaaa ccccgtctct actaaaaagc
    24901 caaaaattag ctgggcgtag tggcgtgcac ccatagtccc agctactcag gaggctgagg
    24961 caggagaact tgcttgaacc ctggaggtgg aggttgtagt gagccgagat cacgccattg
    25021 cactccaact ccaacctgca ggacagagcg agactctgtg ttgccagaaa agaaactatg
    25081 tctctttttt ataaagaaga gaaatagtac atattcctgt ctgagtttca ttggcactag
    25141 taggcatttg gggagctgcc gaacgctggg tgatgagtga atcagtgaca acagtgggtg
    25201 aaccgaggct tagagtttca gcaggtggtc tcagtaacca tcagataaaa ctggtttcag
    25261 gttgccccag gcagtttcaa caatcaggcc tcagagcagt acattcttgg aaccatgttt
    25321 tctatcctga gttctggatg gtctccctac ctggcactct tccttagttg ggtgtgacaa
    25381 gggtgaccca atttgtatgc tcacctttca caccgaatcc tcagctcgga caggtttccc
    25441 tgtctaggct ttgactttcc ccttgaacct catcccacac acctgttcca tcggggccac
    25501 tggcttatga tggagaccag tggtatgact gtggcaggct ccttctaggg gcactctgtc
    25561 tcctgggatc tgccacactg ggggggattc tacttggcct tctctgactc cccagggtcc
    25621 ctcccaccac agcacttgga ggctcttcca tgggaaaact gtcttgatct ttaggtacct
    25681 ggagattctg ggccactttg gttccccatg agccaagacg gcacttctaa tttgcattcc
    25741 ctaccggagt ccctgtctgt agccagcctg gctttcagct ggtgcccaaa gtgacaaatg
    25801 tatctgcaat gacaaaggta ccctggaagg gctcgccctc tgcggaattt cagttcatgc
    25861 aggccttggt gcttccacat ctgtccaagg gcctttcaaa tgtgactttt aactctgtgg
    25921 attgatttgc ccggttgtca cattctgagc agccacaacc tactgcatcc catgtagaag
    25981 tggaagtgac ctgatttttt cctgcttttc aaggctgtat gtttacattt gcctccaatc
    26041 attcctatgg gaattccttg ggagtctaac ttggagattt tgtttcttct gcctttgctc
    26101 ctgggggctt aatcacttct gtgcctctgg ttatctgtgg cacatttgta tttgtcatta
    26161 gtcaaccgga gactcggggt ctgagtggag ggtatgtccc cctccagtga tggtttctgt
    26221 tggcttccca gggtgaggat gactcatgac cacttgcaag tggtttttgt gtctggggtt
    26281 tatgatcaca cagtcataca cgttctaact ccagactgac tgttgagaaa gcctctgggt
    26341 aagggaattc ctgggaaaca cactgttttc atgcatcctc tggaagatga ggcctgaagt
    26401 taccagggtc tctgtttgct gatgctgatg atccacattt tctagcccac tctgcttctc
    26461 tgacaccttt agtcttgagg atccatgntc tgtgaaggaa tccaagctct catttcgcac
    26521 tcaccttggc cctggctctg tctccaggac ctcttctact acaaaatcct aaagctctgg
    26581 gagctgggtg tcaacctgtg cccgaggaaa tcatacagtt actgtggact ttccagtttg
    26641 ctgtcttcta gtattccatt gtagctcttg ggtattttcc catccacccc aagatccagc
    26701 tggaaatcag tgaacacact tgatgggagt tttcctgcat gtgctctggg cattgacagt
    26761 agaagggtgt tcagaatgtc tgctgtgccc tcatggagga agagngctca gtgtacatgc
    26821 tctgggtcag taggtgccct tgagcccagc tttgggagca atgttggatg agtgaaggag
    26881 ggatccaggg caaagcaggc acgacagagt ggagacggcg ctgctggctc tcaggggaat
    26941 gggcatggag tgggtaggag atccacctaa ggaggctggc tggctggacg agtcaggagc
    27001 cccttccaag ggtggacact gacaggcccc cagtcttggt ctcctgcatg ccagaggtac
    27061 cagcccatct tttttcctaa acttgatgac ctagggctag gggcatgttg aatctcagcc
    27121 tcgcccactg gcgctggact tggtacacag ggtggggcaa agtgggtact ggatcctgat
    27181 catccctatc cctggggtgt ggcttcttgc tgcacagtca gcttctagtt ctgtagcccc
    27241 agctgctcct gcggtggagg gagctacaca tcaggctctg accccctcca ggtggggcct
    27301 tcgcgtgagg ggagtcagca cgcatcagca gctgggccca gggagttgcc ccactgagca
    27361 ctgcgggctg acctgctccc aaccagggag atggagcttc ccccttgagt cgggctgctg
    27421 aaggggggta ggggatggaa acagtgcgtt tgcaggagta agggtgcagt tgggtccctg
    27481 cgagaaaatg tctcagttgt ggcaactgat tggtgacctg gggggcgttt ctgagcccac
    27541 agtgctggca tcaggactca ggtgtgaggt gccccagacc ctccccttgc cagtaattag
    27601 ctgatggctc ggtgatgccc agggtgaagg aagacttgat tttgggaggg gagttctctc
    27661 gtaatgacac tgaggatgcc ttcaagttgg gcttctggca tgttctgccc tcgctcccct
    27721 tctgtagtca ccttggccct cgtgttgctg agctgtgtgt gggagcggga agcgcgtcag
    27781 tgggcggagg gagcgggaag cgcgtcagtg ggcggagtat ttgagaacat ttcacaagcc
    27841 gctgttgagg ttcagaatca accagcagat acagaaacat atttcggagc gtggggaccc
    27901 ttgggtgagc tgccacatga agcagcccca ggacctccct ggctcaagga gtgacagcga
    27961 gtttgtctga ggtgagggca caggcctggc gaagcctcgt gtgtgggtga gacctgcccg
    28021 accccagtgc cttacccgag gagctactgg cccagtgggg gaggcattca ggtgggcaga
    28081 gtcagggaga ctcatgaggc cgttgaggcc aggggcatag agctggccaa ggagccatgg
    28141 ctcactaacg tgttgtatgg ggctccttcc cttcaggtcc aggctcctgc gtgaagtgat
    28201 gctcctcttt gccttactcc tagccatgga gctcccattg gtggcagcca gtgccaccat
    28261 gcgcgctcag tgtaagtatc attccctctc actgtcctgg agaggacgag aattccacct
    28321 ggggtgctgg gggtcactgg gatgattggc tgcaacgtgg agcaagcctc cgttagctgg
    28381 ggcctgcatt gtctgtgtaa tcaggggtgg gcactagggc agtccaggag tagtcatgag
    28441 caaggagagg gttaggatga aggagcagct gaccagggac caagggggaa ccttgatgtg
    28501 gcccttcccc atcagcgcca ggcaggaggg gctctgtcca gggaaaccca ggaggatggc
    28561 ggacccctgt gagtatccag tcttccttgg cgaggtgagc caggtctgca gagcatagca
    28621 atcccgtatg tgaccaccaa gtggcgctct ctggagcctg cgttggagag cagggaaagc
    28681 tctccttgtg cctggcctcc ctcccaggag ctagcctggg ccagactcag actgcataga
    28741 gagctgagct gtgcaggcta ggagaagtcc ttggaagcag aggggaaggg ctggccgctg
    28801 aagaagggtg gagtgagctg gtaatgggtg gaaaaggcgt agtggagcag aagcctgaag
    28861 cctgctttct cccctctcag ggacttacag tttgagatgc catgactgtg cggtcataaa
    28921 tgacttcaac tgtcccaaca ttagagtatg tccgtatcat attaggcgct gtatgacaat
    28981 ctccattcgt aagtacctct tggtcatttg gacacattgt agattagtcc cctacctggg
    29041 tagtttctgg ggccagggcc agtctgcttt cttctctgaa cccagctctg tttccccttc
    29101 cctcatgtcc tcccatcctg agtgcgtttc tgcacgcttg ggtctcagcc tcatgatagg
    29161 ccagcatgca tcatcttgtg gagccaggta ctctgcaaag tagtacagtc tgtccacaca
    29221 tctgcagcgt ctccaggggg tgggagcatt gttggaccgc agagcctcta ctgtccctgg
    29281 ttgtgtgtgt agacacccca tgctgcctgg gtgagtcctc actggccatt caatttctgg
    29341 tagtttagag agtgcttcca gttcggaagg tcaaagaagt ggttgggcca tggcactccc
    29401 cccagggaaa aacctaccac acacagttgg gagacaagca tgaggtcagg gcacagcctg
    29461 cacttccagg atgctcttgc tttttcctca gagccctctg gtgccctctc tccccagggc
    29521 cctaacctgc agaagatgta tggccagagg ccagtgacca atggagcaag cagggagggt
    29581 gcagccagtg tatgccctgg cgcacaggtg gagcctcgtc tggggctctg ctcagggcct
    29641 ttcctgtagc ccttttgtcc ccggagtctg tggttgtgct tgcaacttca catgtcattc
    29701 tgtgttctaa gctttgtgca gaaataatcc cctgattacc acctcggtgt ggttgggtta
    29761 tgtccccacc cagatctcat cttgaattgt aactcccata atccccgtgt gtcatgggag
    29821 ggacctggtg ggaggtaatt gattcatctg ggtggttacc ctcatgatgt gctcgtgata
    29881 gcgagtgccc acaagggcga aacctgccac acacagatgg gccggacaag catgcggtgc
    29941 agggcacaga ctgcacttcc aggatgctct tgctttttcc tcagagcccg ctggtgccct
    30001 ctctccccag ggccctaacc tgcagaagat ctgatggttt tctaaggagg gttttccccg
    30061 gaacttctcc tgcctgccat cattcgaaga atgtgttggt tacccctgct gttgtcatcg
    30121 taagtttcct gaggcctccc cagccacgcg gaactgtgag tcagttaaac cgcttgcctt
    30181 tataaattgc ccagtctcgg gcagttctta tagcagcgtg agaagagatc atacacacct
    30241 cttcttcaga ccaactgctg atttgggaca tgggcaggag gctgagaatc tgggctttgt
    30301 ctccacagtg gccactgctg gggaccttga tggcatggtt ttgtcatgtt gggattactg
    30361 cctctaaatg aggctgagaa ctatctttcc cataactccc tcgtggggta atagttggca
    30421 aaaagaggaa cttgagtgag attcgcaagg tatgggtgaa gcagagatca ctcttctgga
    30481 aggtcacgat ggtttagtga agtgaaggac actggtggac tccaatctgt cctccttcat
    30541 gtccacccca tcttctccac tttgtgagcc tttgactgaa agcaattcta agactccagc
    30601 aggcatttgg ccactggcct gcctaggtga tgggttctcc agtggcgcag gttaaatgtc
    30661 tctgcaagag actcctctgc acagccttac ttgagaggat aacggtgcat ggcctttgat
    30721 attgccctgc agagttgggc tgtgccagcc tgccccagtg taagtgacct agctctggac
    30781 tgttgctcct ctgatcttca gccttacctg actgacttcc tctcttggct cccccatggt
    30841 catggcagct gcaacacttt tatttaataa cttagaccta gactgtttta gaggctccat
    30901 tttcctgaat gaaccctgat ggatattagg acaaagaaat tgggaatgct ggaatgctgg
    30961 gacatttttc ctttcaggag atttgctgat ttctggggct gtgcaggatg gtaagcaaaa
    31021 gacctctatg gaaagaaacg caggcagtgt cctgagacaa ggggcctggg tatgaggcat
    31081 ataggaactc tgcactatct ctgcaacttt tctgaaaacc taaaactatt tttaaaataa
    31141 aaggttcata cacacacaca cacacacaca cacacacaca caccataacc ccactacctt
    31201 gtggattcaa taacagaatt gcaatgtggt ttacaatttg aaacccatca gtttaattca
    31261 ccatattaac aaagaaaagg gcagagatga ttgtagatgc tgaaatgttt tgataaaatc
    31321 caacaccctt tccaaatctc tgagggaaat gtctaccatc accacttcta ttcccaatgg
    31381 aactggagtt gttaggtagt tcagttaggc gagggggagt attaagtctc atggagcgga
    31441 ggaagcaaga atttaacctg cttactattc atnagagaca accaacttcg aataacaaat
    31501 atctttaggc aagctcctgg agacaagata agtattccga aatcagttta ccaaatcagt
    31561 tctccttttg tacatcaaga aacagattgg aaatgaaatc cgaggcatgg tgctctttaa
    31621 agtatngcca aatcaagtac cacaaatcta gctggagttg tgcaagattt caacactcaa
    31681 cctgcaagaa cactattgaa gacttaaaac accattaaag acttaaacac atggaattgt
    31741 acacgatact tatggatcat gagaatcnaa cagagtaagg atatctcttc tccaattaac
    31801 ctacaaatcc aacagaattt cagtcaaagt ctcagcaggg gtatgtttgt gttttgacaa
    31861 gttggtgccg aatgcttttt gaaaatatga agggctagga ataaccaaag cagtcttggg
    31921 gaaaaagaaa aaagctcgag gacttgtgct ctgaactata aaaccggttt ccttaatcaa
    31981 aacggtttgg tgttggatcc tgtggtcagg attgaaaaat aacaacatta gaagagaaat
    32041 aattcagaaa aagccacata cttctggttt cttgatctct gacaaagttg tccctgcagt
    32101 gcagcaggta aagacacttc tctgcgctga gcagtagtgg atatgttaga tatttataca
    32161 caatatctgc accatataaa agaagcagtt tcaggtggtt tgtagatctc aatgtaaata
    32221 ttaaaccaat aaagttttta gagaaaaatg taagttgctg tctttatgac ttgtaggaat
    32281 taagaattta aaaaatcgaa caaaatagtg ctagtcacat aagaatgaaa ttgataggtt
    32341 gaattacctc taacttcaaa acttctgttc ctaagaagat acctgtgaaa tagtataacc
    32401 gcaagccacg gatgaggaga aagcatttca aaacatgtat ttactaaagt acttgtgttc
    32461 ataatataat gaacttattc ctatgaatta ataaaaaact gatcaatgga aatttaaaga
    32521 aaaggtttaa agggaattgg ccagaaaatg gtgtctggat gtgtaacaga cataagcgca
    32581 gttgttccct gtcgttcttc ttgaaaggaa tgcagcttaa aaccacaaca caataacgcc
    32641 acaggaaatg actcagtatc ctaaagtgat cataccaagt gttgtcaggg ttctgaactg
    32701 tgcacaatcc ctcagactat agataagttc aacccagtgt agaaaactct tcgatgttgt
    32761 cggctaaagc tgcgtatcca acactgagac tcagcgcttc tactcctagg tacatagcta
    32821 attataaaaa agcttataca ggctcacctt aaggcgaata caagacaaga gtattcattg
    32881 cagcactatt tggagtagac aaaaaccaga aacaacctca atgtccatca acaataaatt
    32941 gtggtatgtt caccaatgta atgctatgca attttgagaa tgaacaatat acaacagtgt
    33001 gcaacaatag ggataaattt cataaacaca gattagagca aaagaagcca tccacaaaag
    33061 cagatgtaat gtataatttc atttcataaa gttcaaaacc aaacagaact aacctatagg
    33121 tttagaagcc catacatttc ctgtctttgg cctgggctgc tcacagcagt gtctgcatgg
    33181 aggaacagag tgaagaatcc tggggctctc tcttgcagct ctgtttctga tgctgcatgc
    33241 tgagtactgc ctgtgggcac ttggtgacaa tccattgagt tgtggacgta tggtcaggca
    33301 catttctgta gaatggtgaa ccccaataaa ctttttaaat ggaaaataac agaaaacaag
    33361 tgactggttc gtattcatca tttgtttctg gtgttataga ggagacaaga cccagaccca
    33421 tgaatagata aatcaattat ggtaagttcc agaataaagt atttgtgtaa acactggata
    33481 gacttcaagg ggaacagaag tagtgatgag ggccaaggta tttaaccctg ggattcttga
    33541 aggaggtctn agatggaact ttggtcaggt gccattggtc aactgaggcc cctggacaag
    33601 ccctctagtg aagattattg atcacattag tcgtgatcac attagttgcg atcgataacc
    33661 ttcaccagag ggcttgtcca tcggataaca cgtacctagt tggaaaggtg catcaagtct
    33721 gtactgggga ggaggttggc accaagggtc aagagcattt atatgttggt ccaggagagc
    33781 tgaaacacca ggctgagggt cccaggaagg agtttacccg agaggggtct tgccaactgc
    33841 agaaaatcta gttaaggcta cattaatagg gacacctctg ttaaaggtcc atgtgatctc
    33901 tagaccataa gtgaaacatg atttctggtc tgcatttaat ttctcgggct ctagaattct
    33961 taccataaga aatgaacagg acatttcatt gcgtgtagct acatgancaa ggtaccatga
    34021 taccattttg ggagggccag agncaannag aatgggcagc tctagnatag aaaactatct
    34081 ccagaagaag ttgttctggg agtgatgaga gcccgctagt ggacttggat gttctctctt
    34141 agtcaagtgt tctagacaat tttatcacag cgtgggagtg tagaatgtgt acatggagct
    34201 aattatggtt gaatgtgagg tgtatgtgcc tcaatattta caagcagaaa atgtgaaatc
    34261 aattattttc attgctgctt ctttttttag gcataaattc tcgtgaacta cttgtttata
    34321 agaactgtac aaacaactgc acatttgtat atgcagctga acagcctcct gaagccccag
    34381 gaaaaatctt caaaactaat agcttctact gggtttgttg ttgtaatagc atggtttgca
    34441 atgcaggagg acctactaat cttgaaaggg acatgttacc cgatgaagta actgaggagg
    34501 agcttccaga aggaactgtg aggctggggg tatcaaaact gttgctgagt tttgcctcta
    34561 tcatagtcag caatatattg ccatgaggac cccaccttgg agggtctgac catcttcacc
    34621 tgttccgcag agaaatgttg ctctccatta ttcccttcta agccagagac ccttatccac
    34681 tgctcctcta ggtggcccat ttatggtttg ttgtaagaga aaaattaaaa aaatattgtt
    34741 tagtggagat gttcatgagc atttgtttgc ctgcatgtac ttgagcactc atagtggagt
    34801 ctctattcat atctgttctt ccctcccttg ctctgtattc agggattact ttgtggtttt
    34861 attataatca gttgctgtag ctattaattg attttggtag ttttgtcttt gtgcttcata
    34921 ctaaagttat gagtgggttg cacactgcag ttatagcatt gcaatatttt ggtttgtctg
    34981 tgtacttaat tttaccctag gttttatact ttcagatgtt ttctttttat acgtgagtgt
    35041 ttttttcttt cagtttgaag agctcccttt agcatttctt gtaagacaga tgtggtggtg
    35101 gtgaattctc tcagcttttg tttgggagag atttatttct ccttcatatt tgaagttcag
    35161 ttttgctgga tacattattc ttggatgaca gttgaggatt ttttttttct gttcaacact
    35221 ttcaaaatgt cataccactc actcctggcc tgttgagttt cccttaagaa ttctgttgcc
    35281 agatgaactg gagctgcttt acatgtctgc ctattttctc ttgccacttt tagggtcctc
    35341 tttttgtcct tgacctttaa gagttttgat tattatatgt gtcagggtag tcctatttgg
    35401 gtcagatctc tttggtgttc tctaactttc ctgtatctga atatttatct cttcttcaag
    35461 ttttggaaat ttttctgtta ttattttttg aacagcttcc tacccctggt gcttgcttaa
    35521 ctccctctta aacaccagta attcttagat ttggtctttt gaggtaattt tctatatctt
    35581 ataggttatc gtcattcctt ttcattcttc tctctttttt ctcctttgtg tactttcaaa
    35641 tagctgtctt caggttcatt gattcttacc tctgctttat ttattttgct gttgaaagcc
    35701 tgtaatgaat ttttcagttc agcaaatata tctctcattt ccaaggtttc tatttgactt
    35761 tttagattat ttcaatgtct tcgttaatta tttctcctaa atttctgaat tgcttttctt
    35821 tgttatcttg gagatcactg agtttcctta aaactactat ttt');

insert into CDS values ('AB002137','1 tcgcgagcgt ctctgggacc ggaagtgcgg gcgagcgcgg gtccccgggt ctgacaggag
       61 cagcctgtgg gcaccgcggc ggtagttgga ggcgggagag ggtccgtagc cgcgccgccc
      121 tgccccgcca tgggcctcct gtcggacccg gttcgccggc gcgcgctcgc ccgcctagtg
      181 ctgcgcctca acgcgccgtt gtggtgagga cagggcccgg ggaggcgggg acccgagggc
      241 cctgggctcg cgccggcggc cccatgcgcg gtccccatcg agggccgggg ccgctccagc
      301 tgctcgcgcc cctccggctg ctcgcgccct tccgctcctg ccctctggaa gcactgaggg
      361 tatcaggccc aggcttaggg ctcgggtccg gcgtcccgat gcaggactcc gggtttaggt
      421 ctcccagacc cgcgcgatcg accccgggtg cggaggttgt ggcctcgggt cggcgtctga
      481 ggacccgctg acgctccggt gcccctccgt cctctctcac agcgtgctga gctacgtggc
      541 gggcatcgcc tggttcttgg cgctggtttt cccgccgctg acccagcgca cttacatgtc
      601 ggagaacgcc atgggctcca ccatggtgga ggagcagttt gcgggcggag accgtgcccg
      661 ggcttttgcc cgggacttcg ccgcccaccg caagaagtcg gggtgagcgg cagagcaggg
      721 cgtatggggc gagcagtggt ggctaaggcc ggggagctct gctcagaggc tcccttcgtg
      781 tctgcagggc tctgccagtg gcctggcttg aacggacgat gcggtcagta gggctggagg
      841 tctacacgca gagtttctcc cggaaactgc ccttcccaga tgagacccac gagcgctatg
      901 tactggggga gtggggtgtg cctgggccca gaaagcacct tggagggagg ggtctgggct
      961 gggtatcacc ttgcgggggt gtcatggggc caggaagctc agtgggaggg aaatccctgg
     1021 tgggcactgg agggctagga aagttgtggg gggcccttca gccccctacc acaaagttac
     1081 actgaggctc cccccaccga tgctgcatac agatggtgtc gggcaccaac gtgtacggca
     1141 tcctgcgggc cccgcgtgct gccagcaccg agtcgcttgt gctcaccgtg ccctgtggct
     1201 ctgactctac caacagccag gctgtggggc tgctgctggc actggctgcc cacttccggg
     1261 gtgagtctca gggctgctgg ccgtggaggg gtttggtcag tgccccagac cctgctgatc
     1321 ctgcttctgg cctccagggc agatttattg ggccaaagat atcgtcttcc tggtaacaga
     1381 acatgacctt ctgggcactg aggcttggct tgaagcctac cacgatgtca atgtcactgg
     1441 taggttctct tgtcctgcct gccctggtcc ccctctcagg gtcactgtcc tcaccacgtc
     1501 ctccattagc actcattcac ttgctcctac aggcatgcag tcgtctcccc tgcagggccg
     1561 agctggggcc attcaggcag ccgtggccct ggagctgagc agtgatgtgg tcaccagcct
     1621 cgatgtggcc gtggaggggc ttaacgggca gctgcccaac cttgacctgc tcaatctctt
     1681 ccagaccttc tgccagaaag ggggcctgtt gtgcacgctt cagggcaagg tggggctgcc
     1741 tgcctgcctg agggctgaag ggcacagggt ctgtgggagg ggctgtctca tcctgtcctg
     1801 cacctctaaa gctgcagccc gaggactgga catcattgga tggaccgctg cagggcctgc
     1861 agacactgct gctcatggtt ctgcggcagg cctccggccg gccccacggc tcccatggcc
     1921 tcttcctgcg ctaccgtgtg gaggccctaa ccctgcgtgg catcaatagc ttccgccagt
     1981 acaagtatga cctggtggca gtgggcaagt aagtagtctc tggtcccccc tttccatgcc
     2041 caggatgggg tctagctgga gcggagtggg ggatggcctg gtggctctgg ccagccgtga
     2101 acctgcccca cacctgacag ggctttggag ggcatgttcc gcaagctcaa ccacctcctg
     2161 gagcgcctgc accagtcctt cttcctctac ttgctccccg gcctctcccg cttcgtctcc
     2221 atcggcctct acatgcccgc tgtcggcttc ttgctcctgg tccttggtct caagatatcc
     2281 tctgcccctt gccatctacc tgtgaccagc ctccagtctc ctcaactcta ggctggggag
     2341 agtcttccat cctgatgggg ggtggggtac gggggtgagc cctgggtccc cctctgggca
     2401 gatcccgtta cacctcttgt tggggtcctt gattgggcta cgctctggaa ctgtggatgc
     2461 agctgcatga ggctggaatg ggccttgagg agcccggggg tgcccctggc cccagtgtac
     2521 cccttccccc atcacaggtg atggcacccc cttctgttgt tggaatgggc ttctggggtc
     2581 tgactggtgt ttagtgttgc aacttagcct cagctggtgg gatggtggtg gtctttgggg
     2641 atcccctggc cccagggtcc atctccaaga gcctgtgtgc cctgcagggt gtggggctgg
     2701 cctcgctcgt ggcacctctg ctgatctcac aggccatggg actggccctc tatgtcctgc
     2761 cagtgctggg ccaacacgtt gccacccagc acttcccagt ggcagaggct gaggctgtgg
     2821 tgctgacact gctggcgatt tatgcagctg gcctggccct gccccacaat acccaccggt
     2881 aagaggctgg gctggttgtt gggggcaggg gtagaggtcc cctggacatg cagacagctt
     2941 gtgggttgcc tctgagtcct ttgtcttaca gggtggtaag cacacaggcc ccagacaggg
     3001 gctggatggc actgaagctg gtagccctga tctacctagc actgcagctg ggctgcatcg
     3061 ccctcaccaa cttctcactg ggcttcctgc tggccaccac catggtgccc actgctgcgc
     3121 ttgccaagcc tcatgggccc cggtatgtat ggatcagccc cacttccccc aatgcctgtg
     3181 ccctcatcac agaccgcacc ctcattcagt agccctttcc cccaacctgg tgcccatgcc
     3241 cccaccatgg agcctacctt gatgttgctt ctccacccag gaccctctat gctgccctgc
     3301 tggtgctgac cagcccggca gccacgctcc ttggcagcct gttcctgtgg cgggagctgc
     3361 aggaggcgcc actgtcactg gccgagggct ggcagctctt cctggcagcg ctagcccagg
     3421 gtgtgctgga gcaccacacc tacggcgccc tgctcttccc actgctgtcc ctgggcctct
     3481 acccctgctg gctgcttttc tggaatgtgc tcttctggaa gtgagatctg cctgtccggg
     3541 ctgggacaga gactccccaa ggaccccatt ctgcctcctt ctggggaaat aaatgagtgt
     3601 ctgtttcagc agctatttga gctcctggcc cgctgtccgt gtagggcccc agggcatggg
     3661 ggtgagaagc ctctgtctgc agggcttggc attcctcaca cctcctccct ggcaagggct
     3721 gctgtagtcc acttactggg tagcattcct gccgaccagg gctctgctgc tgcatcaggt
     3781 gcactctcag ccctggcggg tgccatgcag gctcagaggg ctgtgtgcat tgctctgtgg
     3841 tactgtgcca ggagcggtgc tgggaaggag aatacaccat agccatggtt tgagggcctg
     3901 ccaggagctg aggcacccag aaaccaccta acaccatctt tactgctagg actgaggctg
     3961 gagctggagc cctgcagagg aggcccaggg tgcatggcat ggggcccagg caaggccatc
     4021 gccttggtgt gggattggga tggagcaggg aaggagcacc cggcctggct tcctcagagt
     4081 tgagtcagcc caggtga');
